package com.daniel.www.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.daniel.www.greendao.model.GDUserInfo;
import com.daniel.www.greendao.model.GDUserInfoMore;
import com.daniel.www.greendao.model.GDUserLanguages;
import com.daniel.www.greendao.model.GDUserServices;

import com.daniel.www.greendao.dao.GDUserInfoDao;
import com.daniel.www.greendao.dao.GDUserInfoMoreDao;
import com.daniel.www.greendao.dao.GDUserLanguagesDao;
import com.daniel.www.greendao.dao.GDUserServicesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gDUserInfoDaoConfig;
    private final DaoConfig gDUserInfoMoreDaoConfig;
    private final DaoConfig gDUserLanguagesDaoConfig;
    private final DaoConfig gDUserServicesDaoConfig;

    private final GDUserInfoDao gDUserInfoDao;
    private final GDUserInfoMoreDao gDUserInfoMoreDao;
    private final GDUserLanguagesDao gDUserLanguagesDao;
    private final GDUserServicesDao gDUserServicesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gDUserInfoDaoConfig = daoConfigMap.get(GDUserInfoDao.class).clone();
        gDUserInfoDaoConfig.initIdentityScope(type);

        gDUserInfoMoreDaoConfig = daoConfigMap.get(GDUserInfoMoreDao.class).clone();
        gDUserInfoMoreDaoConfig.initIdentityScope(type);

        gDUserLanguagesDaoConfig = daoConfigMap.get(GDUserLanguagesDao.class).clone();
        gDUserLanguagesDaoConfig.initIdentityScope(type);

        gDUserServicesDaoConfig = daoConfigMap.get(GDUserServicesDao.class).clone();
        gDUserServicesDaoConfig.initIdentityScope(type);

        gDUserInfoDao = new GDUserInfoDao(gDUserInfoDaoConfig, this);
        gDUserInfoMoreDao = new GDUserInfoMoreDao(gDUserInfoMoreDaoConfig, this);
        gDUserLanguagesDao = new GDUserLanguagesDao(gDUserLanguagesDaoConfig, this);
        gDUserServicesDao = new GDUserServicesDao(gDUserServicesDaoConfig, this);

        registerDao(GDUserInfo.class, gDUserInfoDao);
        registerDao(GDUserInfoMore.class, gDUserInfoMoreDao);
        registerDao(GDUserLanguages.class, gDUserLanguagesDao);
        registerDao(GDUserServices.class, gDUserServicesDao);
    }
    
    public void clear() {
        gDUserInfoDaoConfig.getIdentityScope().clear();
        gDUserInfoMoreDaoConfig.getIdentityScope().clear();
        gDUserLanguagesDaoConfig.getIdentityScope().clear();
        gDUserServicesDaoConfig.getIdentityScope().clear();
    }

    public GDUserInfoDao getGDUserInfoDao() {
        return gDUserInfoDao;
    }

    public GDUserInfoMoreDao getGDUserInfoMoreDao() {
        return gDUserInfoMoreDao;
    }

    public GDUserLanguagesDao getGDUserLanguagesDao() {
        return gDUserLanguagesDao;
    }

    public GDUserServicesDao getGDUserServicesDao() {
        return gDUserServicesDao;
    }

}
