package com.daniel.www.greendao.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.daniel.www.greendao.model.GDUserInfoMore;

import com.daniel.www.greendao.model.GDUserServices;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GDUSER_SERVICES.
*/
public class GDUserServicesDao extends AbstractDao<GDUserServices, Long> {

    public static final String TABLENAME = "GDUSER_SERVICES";

    /**
     * Properties of entity GDUserServices.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, String.class, "user_id", false, "USER_ID");
        public final static Property Service_code = new Property(2, String.class, "service_code", false, "SERVICE_CODE");
        public final static Property User_info_id = new Property(3, long.class, "user_info_id", false, "USER_INFO_ID");
    };

    private DaoSession daoSession;

    private Query<GDUserServices> gDUserInfoMore_Rp_UserInfoToServicesQuery;

    public GDUserServicesDao(DaoConfig config) {
        super(config);
    }
    
    public GDUserServicesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GDUSER_SERVICES' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'USER_ID' TEXT," + // 1: user_id
                "'SERVICE_CODE' TEXT," + // 2: service_code
                "'USER_INFO_ID' INTEGER NOT NULL );"); // 3: user_info_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GDUSER_SERVICES'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GDUserServices entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(2, user_id);
        }
 
        String service_code = entity.getService_code();
        if (service_code != null) {
            stmt.bindString(3, service_code);
        }
        stmt.bindLong(4, entity.getUser_info_id());
    }

    @Override
    protected void attachEntity(GDUserServices entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GDUserServices readEntity(Cursor cursor, int offset) {
        GDUserServices entity = new GDUserServices( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // user_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // service_code
            cursor.getLong(offset + 3) // user_info_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GDUserServices entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setService_code(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUser_info_id(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GDUserServices entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GDUserServices entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "rp_UserInfoToServices" to-many relationship of GDUserInfoMore. */
    public List<GDUserServices> _queryGDUserInfoMore_Rp_UserInfoToServices(long user_info_id) {
        synchronized (this) {
            if (gDUserInfoMore_Rp_UserInfoToServicesQuery == null) {
                QueryBuilder<GDUserServices> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.User_info_id.eq(null));
                gDUserInfoMore_Rp_UserInfoToServicesQuery = queryBuilder.build();
            }
        }
        Query<GDUserServices> query = gDUserInfoMore_Rp_UserInfoToServicesQuery.forCurrentThread();
        query.setParameter(0, user_info_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGDUserInfoMoreDao().getAllColumns());
            builder.append(" FROM GDUSER_SERVICES T");
            builder.append(" LEFT JOIN GDUSER_INFO_MORE T0 ON T.'USER_INFO_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GDUserServices loadCurrentDeep(Cursor cursor, boolean lock) {
        GDUserServices entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        GDUserInfoMore gDUserInfoMore = loadCurrentOther(daoSession.getGDUserInfoMoreDao(), cursor, offset);
         if(gDUserInfoMore != null) {
            entity.setGDUserInfoMore(gDUserInfoMore);
        }

        return entity;    
    }

    public GDUserServices loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GDUserServices> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GDUserServices> list = new ArrayList<GDUserServices>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GDUserServices> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GDUserServices> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
