package com.daniel.www.greendao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GDUSER_INFO.
 */
public class GDUserInfo {

    private Long id;
    private String user_id;
    private String user_name;
    /** Not-null value. */
    private String login_user_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GDUserInfo() {
    }

    public GDUserInfo(Long id) {
        this.id = id;
    }

    public GDUserInfo(Long id, String user_id, String user_name, String login_user_id) {
        this.id = id;
        this.user_id = user_id;
        this.user_name = user_name;
        this.login_user_id = login_user_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    /** Not-null value. */
    public String getLogin_user_id() {
        return login_user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLogin_user_id(String login_user_id) {
        this.login_user_id = login_user_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
